[package]
name = "amqp0-primitives"
version = "0.0.2"
authors = ["Alexander Reece <github@reece45.com>"]
build = "build.rs"

[features]
default = ["lifeguard"]
amqp0-pregen-primitives = ["amqp0-primalgen", "amqp0-specs", "rustfmt"]
amqp0-build-primitives = ["amqp0-primalgen", "amqp0-specs"]

[dependencies]
nom = "2.0.0"

[dependencies.lifeguard]
version = "0.5.2"
optional = true

[dependencies.clippy]
version = "*"
optional = true

[build-dependencies]
env_logger = "0.3.5"

[build-dependencies.amqp0-primalgen]
path = "../primalgen"
optional = true

[build-dependencies.amqp0-specs]
path = "../specs"
optional = true

[build-dependencies.clippy]
version = "*"
optional = true

[build-dependencies.rustfmt]
version = "0.6.2"
optional = true
