(function() {var implementors = {};
implementors["xml"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='xml/struct.ParserConfig.html' title='xml::ParserConfig'>ParserConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='xml/struct.EmitterConfig.html' title='xml::EmitterConfig'>EmitterConfig</a>",];implementors["amqp_xmlparse"] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='amqp_xmlparse/amqp0/struct.Protocol.html' title='amqp_xmlparse::amqp0::Protocol'>Protocol</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='amqp_xmlparse/amqp0/enum.Parser.html' title='amqp_xmlparse::amqp0::Parser'>Parser</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='amqp_xmlparse/amqp0/enum.VoidParser.html' title='amqp_xmlparse::amqp0::VoidParser'>VoidParser</a>",];implementors["amqp_xmlparse"] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='amqp_xmlparse/amqp0/struct.Protocol.html' title='amqp_xmlparse::amqp0::Protocol'>Protocol</a>&lt;'a&gt;","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='amqp_xmlparse/amqp0/enum.Parser.html' title='amqp_xmlparse::amqp0::Parser'>Parser</a>&lt;'a&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='amqp_xmlparse/amqp0/enum.VoidParser.html' title='amqp_xmlparse::amqp0::VoidParser'>VoidParser</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
