// Generated by build.rs script in amqp0-primitives
// Pre-generated files are used by default. Generation is done with the amqp0-codegen crate
//
// To regenerate, and not use pre-generated files, use: cargo --features="amqp0-build-primitives"
// To format and replace the pre-generated files, use: cargo --features="amqp0-pregen-primitives"
//
// EDITORS BEWARE: Your modifications may be overridden

pub mod access {
    pub trait RequestMethod<'a> {
        type Payload: Default + SetRequestMethodFields<'a>;
    } // pub trait RequestMethod<'a>

    pub trait SetRequestMethodFields<'a> {
        fn set_active(&mut self, _: bool) {}
        fn set_exclusive(&mut self, _: bool) {}
        fn set_passive(&mut self, _: bool) {}
        fn set_read(&mut self, _: bool) {}
        fn set_realm<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_write(&mut self, _: bool) {}
    } // pub trait SetRequestMethodFields<'a>

    pub trait RequestOkMethod {
        type Payload: Default + SetRequestOkMethodFields;
    } // pub trait RequestOkMethod

    pub trait SetRequestOkMethodFields {
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetRequestOkMethodFields

} // mod access

pub mod basic {
    pub trait AckMethod {
        type Payload: Default + SetAckMethodFields;
    } // pub trait AckMethod

    pub trait SetAckMethodFields {
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_multiple(&mut self, _: bool) {}
    } // pub trait SetAckMethodFields

    pub trait CancelMethod<'a> {
        type Payload: Default + SetCancelMethodFields<'a>;
    } // pub trait CancelMethod<'a>

    pub trait SetCancelMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_no_wait(&mut self, _: bool) {}
    } // pub trait SetCancelMethodFields<'a>

    pub trait CancelOkMethod<'a> {
        type Payload: Default + SetCancelOkMethodFields<'a>;
    } // pub trait CancelOkMethod<'a>

    pub trait SetCancelOkMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetCancelOkMethodFields<'a>

    pub trait ConsumeMethod<'a> {
        type Payload: Default + SetConsumeMethodFields<'a>;
    } // pub trait ConsumeMethod<'a>

    pub trait SetConsumeMethodFields<'a> {
        fn set_arguments<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_exclusive(&mut self, _: bool) {}
        fn set_filter<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_no_ack(&mut self, _: bool) {}
        fn set_no_local(&mut self, _: bool) {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetConsumeMethodFields<'a>

    pub trait ConsumeOkMethod<'a> {
        type Payload: Default + SetConsumeOkMethodFields<'a>;
    } // pub trait ConsumeOkMethod<'a>

    pub trait SetConsumeOkMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetConsumeOkMethodFields<'a>

    pub trait DeliverMethod<'a> {
        type Payload: Default + SetDeliverMethodFields<'a>;
    } // pub trait DeliverMethod<'a>

    pub trait SetDeliverMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_redelivered(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetDeliverMethodFields<'a>

    pub trait GetMethod<'a> {
        type Payload: Default + SetGetMethodFields<'a>;
    } // pub trait GetMethod<'a>

    pub trait SetGetMethodFields<'a> {
        fn set_no_ack(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetGetMethodFields<'a>

    pub trait GetEmptyMethod<'a> {
        type Payload: Default + SetGetEmptyMethodFields<'a>;
    } // pub trait GetEmptyMethod<'a>

    pub trait SetGetEmptyMethodFields<'a> {
        fn set_cluster_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetGetEmptyMethodFields<'a>

    pub trait GetOkMethod<'a> {
        type Payload: Default + SetGetOkMethodFields<'a>;
    } // pub trait GetOkMethod<'a>

    pub trait SetGetOkMethodFields<'a> {
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_message_count(&mut self, _: u32) {}
        fn set_redelivered(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetGetOkMethodFields<'a>

    pub trait NackMethod {
        type Payload: Default + SetNackMethodFields;
    } // pub trait NackMethod

    pub trait SetNackMethodFields {
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_multiple(&mut self, _: bool) {}
        fn set_requeue(&mut self, _: bool) {}
    } // pub trait SetNackMethodFields

    pub trait PublishMethod<'a> {
        type Payload: Default + SetPublishMethodFields<'a>;
    } // pub trait PublishMethod<'a>

    pub trait SetPublishMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_immediate(&mut self, _: bool) {}
        fn set_mandatory(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetPublishMethodFields<'a>

    pub trait QosMethod {
        type Payload: Default + SetQosMethodFields;
    } // pub trait QosMethod

    pub trait SetQosMethodFields {
        fn set_global(&mut self, _: bool) {}
        fn set_prefetch_count(&mut self, _: u16) {}
        fn set_prefetch_size(&mut self, _: u32) {}
    } // pub trait SetQosMethodFields

    pub trait QosOkMethod {
        type Payload: Default;
    } // pub trait QosOkMethod

    pub trait RecoverMethod {
        type Payload: Default + SetRecoverMethodFields;
    } // pub trait RecoverMethod

    pub trait SetRecoverMethodFields {
        fn set_requeue(&mut self, _: bool) {}
    } // pub trait SetRecoverMethodFields

    pub trait RecoverAsyncMethod {
        type Payload: Default + SetRecoverAsyncMethodFields;
    } // pub trait RecoverAsyncMethod

    pub trait SetRecoverAsyncMethodFields {
        fn set_requeue(&mut self, _: bool) {}
    } // pub trait SetRecoverAsyncMethodFields

    pub trait RecoverOkMethod {
        type Payload: Default;
    } // pub trait RecoverOkMethod

    pub trait RecoverSyncMethod {
        type Payload: Default + SetRecoverSyncMethodFields;
    } // pub trait RecoverSyncMethod

    pub trait SetRecoverSyncMethodFields {
        fn set_requeue(&mut self, _: bool) {}
    } // pub trait SetRecoverSyncMethodFields

    pub trait RecoverSyncOkMethod {
        type Payload: Default;
    } // pub trait RecoverSyncOkMethod

    pub trait RejectMethod {
        type Payload: Default + SetRejectMethodFields;
    } // pub trait RejectMethod

    pub trait SetRejectMethodFields {
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_requeue(&mut self, _: bool) {}
    } // pub trait SetRejectMethodFields

    pub trait ReturnMethod<'a> {
        type Payload: Default + SetReturnMethodFields<'a>;
    } // pub trait ReturnMethod<'a>

    pub trait SetReturnMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_reply_code(&mut self, _: u16) {}
        fn set_reply_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetReturnMethodFields<'a>

} // mod basic

pub mod channel {
    pub trait AlertMethod<'a> {
        type Payload: Default + SetAlertMethodFields<'a>;
    } // pub trait AlertMethod<'a>

    pub trait SetAlertMethodFields<'a> {
        fn set_details<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_reply_code(&mut self, _: u16) {}
        fn set_reply_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetAlertMethodFields<'a>

    pub trait CloseMethod<'a> {
        type Payload: Default + SetCloseMethodFields<'a>;
    } // pub trait CloseMethod<'a>

    pub trait SetCloseMethodFields<'a> {
        fn set_class_id(&mut self, _: u16) {}
        fn set_method_id(&mut self, _: u16) {}
        fn set_reply_code(&mut self, _: u16) {}
        fn set_reply_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetCloseMethodFields<'a>

    pub trait CloseOkMethod {
        type Payload: Default;
    } // pub trait CloseOkMethod

    pub trait FlowMethod {
        type Payload: Default + SetFlowMethodFields;
    } // pub trait FlowMethod

    pub trait SetFlowMethodFields {
        fn set_active(&mut self, _: bool) {}
    } // pub trait SetFlowMethodFields

    pub trait FlowOkMethod {
        type Payload: Default + SetFlowOkMethodFields;
    } // pub trait FlowOkMethod

    pub trait SetFlowOkMethodFields {
        fn set_active(&mut self, _: bool) {}
    } // pub trait SetFlowOkMethodFields

    pub trait OkMethod {
        type Payload: Default;
    } // pub trait OkMethod

    pub trait OpenMethod<'a> {
        type Payload: Default + SetOpenMethodFields<'a>;
    } // pub trait OpenMethod<'a>

    pub trait SetOpenMethodFields<'a> {
        fn set_out_of_band<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetOpenMethodFields<'a>

    pub trait OpenOkMethod<'a> {
        type Payload: Default + SetOpenOkMethodFields<'a>;
    } // pub trait OpenOkMethod<'a>

    pub trait SetOpenOkMethodFields<'a> {
        fn set_channel_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetOpenOkMethodFields<'a>

    pub trait PingMethod {
        type Payload: Default;
    } // pub trait PingMethod

    pub trait PongMethod {
        type Payload: Default;
    } // pub trait PongMethod

    pub trait ResumeMethod<'a> {
        type Payload: Default + SetResumeMethodFields<'a>;
    } // pub trait ResumeMethod<'a>

    pub trait SetResumeMethodFields<'a> {
        fn set_channel_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetResumeMethodFields<'a>

} // mod channel

pub mod confirm {
    pub trait SelectMethod {
        type Payload: Default + SetSelectMethodFields;
    } // pub trait SelectMethod

    pub trait SetSelectMethodFields {
        fn set_no_wait(&mut self, _: bool) {}
    } // pub trait SetSelectMethodFields

    pub trait SelectOkMethod {
        type Payload: Default;
    } // pub trait SelectOkMethod

} // mod confirm

pub mod connection {
    pub trait BlockedMethod<'a> {
        type Payload: Default + SetBlockedMethodFields<'a>;
    } // pub trait BlockedMethod<'a>

    pub trait SetBlockedMethodFields<'a> {
        fn set_reason<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetBlockedMethodFields<'a>

    pub trait CloseMethod<'a> {
        type Payload: Default + SetCloseMethodFields<'a>;
    } // pub trait CloseMethod<'a>

    pub trait SetCloseMethodFields<'a> {
        fn set_class_id(&mut self, _: u16) {}
        fn set_method_id(&mut self, _: u16) {}
        fn set_reply_code(&mut self, _: u16) {}
        fn set_reply_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetCloseMethodFields<'a>

    pub trait CloseOkMethod {
        type Payload: Default;
    } // pub trait CloseOkMethod

    pub trait OpenMethod<'a> {
        type Payload: Default + SetOpenMethodFields<'a>;
    } // pub trait OpenMethod<'a>

    pub trait SetOpenMethodFields<'a> {
        fn set_capabilities<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_insist(&mut self, _: bool) {}
        fn set_virtual_host<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetOpenMethodFields<'a>

    pub trait OpenOkMethod<'a> {
        type Payload: Default + SetOpenOkMethodFields<'a>;
    } // pub trait OpenOkMethod<'a>

    pub trait SetOpenOkMethodFields<'a> {
        fn set_known_hosts<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetOpenOkMethodFields<'a>

    pub trait RedirectMethod<'a> {
        type Payload: Default + SetRedirectMethodFields<'a>;
    } // pub trait RedirectMethod<'a>

    pub trait SetRedirectMethodFields<'a> {
        fn set_host<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_known_hosts<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetRedirectMethodFields<'a>

    pub trait SecureMethod<'a> {
        type Payload: Default + SetSecureMethodFields<'a>;
    } // pub trait SecureMethod<'a>

    pub trait SetSecureMethodFields<'a> {
        fn set_challenge<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetSecureMethodFields<'a>

    pub trait SecureOkMethod<'a> {
        type Payload: Default + SetSecureOkMethodFields<'a>;
    } // pub trait SecureOkMethod<'a>

    pub trait SetSecureOkMethodFields<'a> {
        fn set_response<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetSecureOkMethodFields<'a>

    pub trait StartMethod<'a> {
        type Payload: Default + SetStartMethodFields<'a>;
    } // pub trait StartMethod<'a>

    pub trait SetStartMethodFields<'a> {
        fn set_locales<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
        fn set_mechanisms<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
        fn set_server_properties<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_version_major(&mut self, _: u8) {}
        fn set_version_minor(&mut self, _: u8) {}
    } // pub trait SetStartMethodFields<'a>

    pub trait StartOkMethod<'a> {
        type Payload: Default + SetStartOkMethodFields<'a>;
    } // pub trait StartOkMethod<'a>

    pub trait SetStartOkMethodFields<'a> {
        fn set_client_properties<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_locale<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_mechanism<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_response<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetStartOkMethodFields<'a>

    pub trait TuneMethod {
        type Payload: Default + SetTuneMethodFields;
    } // pub trait TuneMethod

    pub trait SetTuneMethodFields {
        fn set_channel_max(&mut self, _: u16) {}
        fn set_frame_max(&mut self, _: u32) {}
        fn set_heartbeat(&mut self, _: u16) {}
    } // pub trait SetTuneMethodFields

    pub trait TuneOkMethod {
        type Payload: Default + SetTuneOkMethodFields;
    } // pub trait TuneOkMethod

    pub trait SetTuneOkMethodFields {
        fn set_channel_max(&mut self, _: u16) {}
        fn set_frame_max(&mut self, _: u32) {}
        fn set_heartbeat(&mut self, _: u16) {}
    } // pub trait SetTuneOkMethodFields

    pub trait UnblockedMethod {
        type Payload: Default;
    } // pub trait UnblockedMethod

} // mod connection

pub mod dtx {
    pub trait SelectMethod {
        type Payload: Default;
    } // pub trait SelectMethod

    pub trait SelectOkMethod {
        type Payload: Default;
    } // pub trait SelectOkMethod

    pub trait StartMethod<'a> {
        type Payload: Default + SetStartMethodFields<'a>;
    } // pub trait StartMethod<'a>

    pub trait SetStartMethodFields<'a> {
        fn set_dtx_identifier<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetStartMethodFields<'a>

    pub trait StartOkMethod {
        type Payload: Default;
    } // pub trait StartOkMethod

} // mod dtx

pub mod exchange {
    pub trait BindMethod<'a> {
        type Payload: Default + SetBindMethodFields<'a>;
    } // pub trait BindMethod<'a>

    pub trait SetBindMethodFields<'a> {
        fn set_arguments<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_destination<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_source<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetBindMethodFields<'a>

    pub trait BindOkMethod {
        type Payload: Default;
    } // pub trait BindOkMethod

    pub trait BoundMethod<'a> {
        type Payload: Default + SetBoundMethodFields<'a>;
    } // pub trait BoundMethod<'a>

    pub trait SetBoundMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetBoundMethodFields<'a>

    pub trait BoundOkMethod<'a> {
        type Payload: Default + SetBoundOkMethodFields<'a>;
    } // pub trait BoundOkMethod<'a>

    pub trait SetBoundOkMethodFields<'a> {
        fn set_reply_code(&mut self, _: u16) {}
        fn set_reply_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetBoundOkMethodFields<'a>

    pub trait DeclareMethod<'a> {
        type Payload: Default + SetDeclareMethodFields<'a>;
    } // pub trait DeclareMethod<'a>

    pub trait SetDeclareMethodFields<'a> {
        fn set_arguments<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_auto_delete(&mut self, _: bool) {}
        fn set_durable(&mut self, _: bool) {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_internal(&mut self, _: bool) {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_passive(&mut self, _: bool) {}
        fn set_ticket(&mut self, _: u16) {}
        fn set_ty<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetDeclareMethodFields<'a>

    pub trait DeclareOkMethod {
        type Payload: Default;
    } // pub trait DeclareOkMethod

    pub trait DeleteMethod<'a> {
        type Payload: Default + SetDeleteMethodFields<'a>;
    } // pub trait DeleteMethod<'a>

    pub trait SetDeleteMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_if_unused(&mut self, _: bool) {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetDeleteMethodFields<'a>

    pub trait DeleteOkMethod {
        type Payload: Default;
    } // pub trait DeleteOkMethod

    pub trait UnbindMethod<'a> {
        type Payload: Default + SetUnbindMethodFields<'a>;
    } // pub trait UnbindMethod<'a>

    pub trait SetUnbindMethodFields<'a> {
        fn set_arguments<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_destination<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_source<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetUnbindMethodFields<'a>

    pub trait UnbindOkMethod {
        type Payload: Default;
    } // pub trait UnbindOkMethod

} // mod exchange

pub mod file {
    pub trait AckMethod {
        type Payload: Default + SetAckMethodFields;
    } // pub trait AckMethod

    pub trait SetAckMethodFields {
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_multiple(&mut self, _: bool) {}
    } // pub trait SetAckMethodFields

    pub trait CancelMethod<'a> {
        type Payload: Default + SetCancelMethodFields<'a>;
    } // pub trait CancelMethod<'a>

    pub trait SetCancelMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_no_wait(&mut self, _: bool) {}
    } // pub trait SetCancelMethodFields<'a>

    pub trait CancelOkMethod<'a> {
        type Payload: Default + SetCancelOkMethodFields<'a>;
    } // pub trait CancelOkMethod<'a>

    pub trait SetCancelOkMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetCancelOkMethodFields<'a>

    pub trait ConsumeMethod<'a> {
        type Payload: Default + SetConsumeMethodFields<'a>;
    } // pub trait ConsumeMethod<'a>

    pub trait SetConsumeMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_exclusive(&mut self, _: bool) {}
        fn set_filter<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_no_ack(&mut self, _: bool) {}
        fn set_no_local(&mut self, _: bool) {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetConsumeMethodFields<'a>

    pub trait ConsumeOkMethod<'a> {
        type Payload: Default + SetConsumeOkMethodFields<'a>;
    } // pub trait ConsumeOkMethod<'a>

    pub trait SetConsumeOkMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetConsumeOkMethodFields<'a>

    pub trait DeliverMethod<'a> {
        type Payload: Default + SetDeliverMethodFields<'a>;
    } // pub trait DeliverMethod<'a>

    pub trait SetDeliverMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_identifier<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_redelivered(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetDeliverMethodFields<'a>

    pub trait OpenMethod<'a> {
        type Payload: Default + SetOpenMethodFields<'a>;
    } // pub trait OpenMethod<'a>

    pub trait SetOpenMethodFields<'a> {
        fn set_content_size(&mut self, _: u64) {}
        fn set_identifier<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetOpenMethodFields<'a>

    pub trait OpenOkMethod {
        type Payload: Default + SetOpenOkMethodFields;
    } // pub trait OpenOkMethod

    pub trait SetOpenOkMethodFields {
        fn set_staged_size(&mut self, _: u64) {}
    } // pub trait SetOpenOkMethodFields

    pub trait PublishMethod<'a> {
        type Payload: Default + SetPublishMethodFields<'a>;
    } // pub trait PublishMethod<'a>

    pub trait SetPublishMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_identifier<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_immediate(&mut self, _: bool) {}
        fn set_mandatory(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetPublishMethodFields<'a>

    pub trait QosMethod {
        type Payload: Default + SetQosMethodFields;
    } // pub trait QosMethod

    pub trait SetQosMethodFields {
        fn set_global(&mut self, _: bool) {}
        fn set_prefetch_count(&mut self, _: u16) {}
        fn set_prefetch_size(&mut self, _: u32) {}
    } // pub trait SetQosMethodFields

    pub trait QosOkMethod {
        type Payload: Default;
    } // pub trait QosOkMethod

    pub trait RejectMethod {
        type Payload: Default + SetRejectMethodFields;
    } // pub trait RejectMethod

    pub trait SetRejectMethodFields {
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_requeue(&mut self, _: bool) {}
    } // pub trait SetRejectMethodFields

    pub trait ReturnMethod<'a> {
        type Payload: Default + SetReturnMethodFields<'a>;
    } // pub trait ReturnMethod<'a>

    pub trait SetReturnMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_reply_code(&mut self, _: u16) {}
        fn set_reply_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetReturnMethodFields<'a>

    pub trait StageMethod {
        type Payload: Default;
    } // pub trait StageMethod

} // mod file

pub mod message {
    pub trait AppendMethod<'a> {
        type Payload: Default + SetAppendMethodFields<'a>;
    } // pub trait AppendMethod<'a>

    pub trait SetAppendMethodFields<'a> {
        fn set_bytes<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
        fn set_reference<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetAppendMethodFields<'a>

    pub trait CancelMethod<'a> {
        type Payload: Default + SetCancelMethodFields<'a>;
    } // pub trait CancelMethod<'a>

    pub trait SetCancelMethodFields<'a> {
        fn set_destination<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetCancelMethodFields<'a>

    pub trait CheckpointMethod<'a> {
        type Payload: Default + SetCheckpointMethodFields<'a>;
    } // pub trait CheckpointMethod<'a>

    pub trait SetCheckpointMethodFields<'a> {
        fn set_identifier<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_reference<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetCheckpointMethodFields<'a>

    pub trait CloseMethod<'a> {
        type Payload: Default + SetCloseMethodFields<'a>;
    } // pub trait CloseMethod<'a>

    pub trait SetCloseMethodFields<'a> {
        fn set_reference<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetCloseMethodFields<'a>

    pub trait ConsumeMethod<'a> {
        type Payload: Default + SetConsumeMethodFields<'a>;
    } // pub trait ConsumeMethod<'a>

    pub trait SetConsumeMethodFields<'a> {
        fn set_destination<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_exclusive(&mut self, _: bool) {}
        fn set_filter<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_no_ack(&mut self, _: bool) {}
        fn set_no_local(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetConsumeMethodFields<'a>

    pub trait EmptyMethod {
        type Payload: Default;
    } // pub trait EmptyMethod

    pub trait GetMethod<'a> {
        type Payload: Default + SetGetMethodFields<'a>;
    } // pub trait GetMethod<'a>

    pub trait SetGetMethodFields<'a> {
        fn set_destination<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_no_ack(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetGetMethodFields<'a>

    pub trait OffsetMethod {
        type Payload: Default + SetOffsetMethodFields;
    } // pub trait OffsetMethod

    pub trait SetOffsetMethodFields {
        fn set_value(&mut self, _: u64) {}
    } // pub trait SetOffsetMethodFields

    pub trait OkMethod {
        type Payload: Default;
    } // pub trait OkMethod

    pub trait OpenMethod<'a> {
        type Payload: Default + SetOpenMethodFields<'a>;
    } // pub trait OpenMethod<'a>

    pub trait SetOpenMethodFields<'a> {
        fn set_reference<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetOpenMethodFields<'a>

    pub trait QosMethod {
        type Payload: Default + SetQosMethodFields;
    } // pub trait QosMethod

    pub trait SetQosMethodFields {
        fn set_global(&mut self, _: bool) {}
        fn set_prefetch_count(&mut self, _: u16) {}
        fn set_prefetch_size(&mut self, _: u32) {}
    } // pub trait SetQosMethodFields

    pub trait RecoverMethod {
        type Payload: Default + SetRecoverMethodFields;
    } // pub trait RecoverMethod

    pub trait SetRecoverMethodFields {
        fn set_requeue(&mut self, _: bool) {}
    } // pub trait SetRecoverMethodFields

    pub trait RejectMethod<'a> {
        type Payload: Default + SetRejectMethodFields<'a>;
    } // pub trait RejectMethod<'a>

    pub trait SetRejectMethodFields<'a> {
        fn set_code(&mut self, _: u16) {}
        fn set_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetRejectMethodFields<'a>

    pub trait ResumeMethod<'a> {
        type Payload: Default + SetResumeMethodFields<'a>;
    } // pub trait ResumeMethod<'a>

    pub trait SetResumeMethodFields<'a> {
        fn set_identifier<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_reference<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetResumeMethodFields<'a>

    pub trait TransferMethod<'a> {
        type Payload: Default + SetTransferMethodFields<'a>;
    } // pub trait TransferMethod<'a>

    pub trait SetTransferMethodFields<'a> {
        fn set_app_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_application_headers<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_body<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
        fn set_content_encoding<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_content_type<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_correlation_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_delivery_mode(&mut self, _: u8) {}
        fn set_destination<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_expiration(&mut self, _: u64) {}
        fn set_immediate(&mut self, _: bool) {}
        fn set_message_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_priority(&mut self, _: u8) {}
        fn set_redelivered(&mut self, _: bool) {}
        fn set_reply_to<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_security_token<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
        fn set_ticket(&mut self, _: u16) {}
        fn set_timestamp(&mut self, _: u64) {}
        fn set_transaction_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ttl(&mut self, _: u64) {}
        fn set_user_id<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetTransferMethodFields<'a>

} // mod message

pub mod queue {
    pub trait BindMethod<'a> {
        type Payload: Default + SetBindMethodFields<'a>;
    } // pub trait BindMethod<'a>

    pub trait SetBindMethodFields<'a> {
        fn set_arguments<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetBindMethodFields<'a>

    pub trait BindOkMethod {
        type Payload: Default;
    } // pub trait BindOkMethod

    pub trait DeclareMethod<'a> {
        type Payload: Default + SetDeclareMethodFields<'a>;
    } // pub trait DeclareMethod<'a>

    pub trait SetDeclareMethodFields<'a> {
        fn set_arguments<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_auto_delete(&mut self, _: bool) {}
        fn set_durable(&mut self, _: bool) {}
        fn set_exclusive(&mut self, _: bool) {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_passive(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetDeclareMethodFields<'a>

    pub trait DeclareOkMethod<'a> {
        type Payload: Default + SetDeclareOkMethodFields<'a>;
    } // pub trait DeclareOkMethod<'a>

    pub trait SetDeclareOkMethodFields<'a> {
        fn set_consumer_count(&mut self, _: u32) {}
        fn set_message_count(&mut self, _: u32) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetDeclareOkMethodFields<'a>

    pub trait DeleteMethod<'a> {
        type Payload: Default + SetDeleteMethodFields<'a>;
    } // pub trait DeleteMethod<'a>

    pub trait SetDeleteMethodFields<'a> {
        fn set_if_empty(&mut self, _: bool) {}
        fn set_if_unused(&mut self, _: bool) {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetDeleteMethodFields<'a>

    pub trait DeleteOkMethod {
        type Payload: Default + SetDeleteOkMethodFields;
    } // pub trait DeleteOkMethod

    pub trait SetDeleteOkMethodFields {
        fn set_message_count(&mut self, _: u32) {}
    } // pub trait SetDeleteOkMethodFields

    pub trait PurgeMethod<'a> {
        type Payload: Default + SetPurgeMethodFields<'a>;
    } // pub trait PurgeMethod<'a>

    pub trait SetPurgeMethodFields<'a> {
        fn set_no_wait(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetPurgeMethodFields<'a>

    pub trait PurgeOkMethod {
        type Payload: Default + SetPurgeOkMethodFields;
    } // pub trait PurgeOkMethod

    pub trait SetPurgeOkMethodFields {
        fn set_message_count(&mut self, _: u32) {}
    } // pub trait SetPurgeOkMethodFields

    pub trait UnbindMethod<'a> {
        type Payload: Default + SetUnbindMethodFields<'a>;
    } // pub trait UnbindMethod<'a>

    pub trait SetUnbindMethodFields<'a> {
        fn set_arguments<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetUnbindMethodFields<'a>

    pub trait UnbindOkMethod {
        type Payload: Default;
    } // pub trait UnbindOkMethod

} // mod queue

pub mod stream {
    pub trait CancelMethod<'a> {
        type Payload: Default + SetCancelMethodFields<'a>;
    } // pub trait CancelMethod<'a>

    pub trait SetCancelMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_no_wait(&mut self, _: bool) {}
    } // pub trait SetCancelMethodFields<'a>

    pub trait CancelOkMethod<'a> {
        type Payload: Default + SetCancelOkMethodFields<'a>;
    } // pub trait CancelOkMethod<'a>

    pub trait SetCancelOkMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetCancelOkMethodFields<'a>

    pub trait ConsumeMethod<'a> {
        type Payload: Default + SetConsumeMethodFields<'a>;
    } // pub trait ConsumeMethod<'a>

    pub trait SetConsumeMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_exclusive(&mut self, _: bool) {}
        fn set_filter<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
        fn set_no_local(&mut self, _: bool) {}
        fn set_no_wait(&mut self, _: bool) {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetConsumeMethodFields<'a>

    pub trait ConsumeOkMethod<'a> {
        type Payload: Default + SetConsumeOkMethodFields<'a>;
    } // pub trait ConsumeOkMethod<'a>

    pub trait SetConsumeOkMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetConsumeOkMethodFields<'a>

    pub trait DeliverMethod<'a> {
        type Payload: Default + SetDeliverMethodFields<'a>;
    } // pub trait DeliverMethod<'a>

    pub trait SetDeliverMethodFields<'a> {
        fn set_consumer_tag<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_delivery_tag(&mut self, _: u64) {}
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_queue<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetDeliverMethodFields<'a>

    pub trait PublishMethod<'a> {
        type Payload: Default + SetPublishMethodFields<'a>;
    } // pub trait PublishMethod<'a>

    pub trait SetPublishMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_immediate(&mut self, _: bool) {}
        fn set_mandatory(&mut self, _: bool) {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_ticket(&mut self, _: u16) {}
    } // pub trait SetPublishMethodFields<'a>

    pub trait QosMethod {
        type Payload: Default + SetQosMethodFields;
    } // pub trait QosMethod

    pub trait SetQosMethodFields {
        fn set_consume_rate(&mut self, _: u32) {}
        fn set_global(&mut self, _: bool) {}
        fn set_prefetch_count(&mut self, _: u16) {}
        fn set_prefetch_size(&mut self, _: u32) {}
    } // pub trait SetQosMethodFields

    pub trait QosOkMethod {
        type Payload: Default;
    } // pub trait QosOkMethod

    pub trait ReturnMethod<'a> {
        type Payload: Default + SetReturnMethodFields<'a>;
    } // pub trait ReturnMethod<'a>

    pub trait SetReturnMethodFields<'a> {
        fn set_exchange<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_reply_code(&mut self, _: u16) {}
        fn set_reply_text<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_routing_key<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
    } // pub trait SetReturnMethodFields<'a>

} // mod stream

pub mod test {
    pub trait ContentMethod {
        type Payload: Default;
    } // pub trait ContentMethod

    pub trait ContentOkMethod {
        type Payload: Default + SetContentOkMethodFields;
    } // pub trait ContentOkMethod

    pub trait SetContentOkMethodFields {
        fn set_content_checksum(&mut self, _: u32) {}
    } // pub trait SetContentOkMethodFields

    pub trait IntegerMethod {
        type Payload: Default + SetIntegerMethodFields;
    } // pub trait IntegerMethod

    pub trait SetIntegerMethodFields {
        fn set_integer_1(&mut self, _: u8) {}
        fn set_integer_2(&mut self, _: u16) {}
        fn set_integer_3(&mut self, _: u32) {}
        fn set_integer_4(&mut self, _: u64) {}
        fn set_operation(&mut self, _: u8) {}
    } // pub trait SetIntegerMethodFields

    pub trait IntegerOkMethod {
        type Payload: Default + SetIntegerOkMethodFields;
    } // pub trait IntegerOkMethod

    pub trait SetIntegerOkMethodFields {
        fn set_result(&mut self, _: u64) {}
    } // pub trait SetIntegerOkMethodFields

    pub trait StringMethod<'a> {
        type Payload: Default + SetStringMethodFields<'a>;
    } // pub trait StringMethod<'a>

    pub trait SetStringMethodFields<'a> {
        fn set_operation(&mut self, _: u8) {}
        fn set_string_1<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, str>> {}
        fn set_string_2<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetStringMethodFields<'a>

    pub trait StringOkMethod<'a> {
        type Payload: Default + SetStringOkMethodFields<'a>;
    } // pub trait StringOkMethod<'a>

    pub trait SetStringOkMethodFields<'a> {
        fn set_result<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetStringOkMethodFields<'a>

    pub trait TableMethod<'a> {
        type Payload: Default + SetTableMethodFields<'a>;
    } // pub trait TableMethod<'a>

    pub trait SetTableMethodFields<'a> {
        fn set_integer_op(&mut self, _: u8) {}
        fn set_string_op(&mut self, _: u8) {}
        fn set_table<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
    } // pub trait SetTableMethodFields<'a>

    pub trait TableOkMethod<'a> {
        type Payload: Default + SetTableOkMethodFields<'a>;
    } // pub trait TableOkMethod<'a>

    pub trait SetTableOkMethodFields<'a> {
        fn set_integer_result(&mut self, _: u64) {}
        fn set_string_result<V>(&mut self, _: V) where V: Into<::std::borrow::Cow<'a, [u8]>> {}
    } // pub trait SetTableOkMethodFields<'a>

} // mod test

pub mod tunnel {
    pub trait RequestMethod<'a> {
        type Payload: Default + SetRequestMethodFields<'a>;
    } // pub trait RequestMethod<'a>

    pub trait SetRequestMethodFields<'a> {
        fn set_meta_data<V>(&mut self, _: V) where V: Into<::field::TableEntries<'a>> {}
    } // pub trait SetRequestMethodFields<'a>

} // mod tunnel

pub mod tx {
    pub trait CommitMethod {
        type Payload: Default;
    } // pub trait CommitMethod

    pub trait CommitOkMethod {
        type Payload: Default;
    } // pub trait CommitOkMethod

    pub trait RollbackMethod {
        type Payload: Default;
    } // pub trait RollbackMethod

    pub trait RollbackOkMethod {
        type Payload: Default;
    } // pub trait RollbackOkMethod

    pub trait SelectMethod {
        type Payload: Default;
    } // pub trait SelectMethod

    pub trait SelectOkMethod {
        type Payload: Default;
    } // pub trait SelectOkMethod

} // mod tx
