// Generated by build.rs script in amqp0-primitives
// Pre-generated files are used by default. Generation is done with the amqp0-codegen crate
//
// To regenerate, and not use pre-generated files, use: cargo --features="amqp0-build-primitives"
// To format and replace the pre-generated files, use: cargo --features="amqp0-pregen-primitives"
//
// EDITORS BEWARE: Your modifications may be overridden
pub trait SelectMethod {
    type Payload: Default + SetSelectMethodFields;
} // pub trait SelectMethod

pub trait SetSelectMethodFields {
    fn set_no_wait(&mut self, _: bool) {}
} // pub trait SetSelectMethodFields

pub struct SelectBuilder<T>
    where T: ::Encodable
{
    payload: T,
} // struct SelectBuilder


impl<T> SelectBuilder<T>
    where T: Default + ::Encodable
{
    pub fn new() -> Self {
        Default::default()
    }
} // impl Builder (new)

impl<T> SelectBuilder<T>
    where T: ::Encodable
{
    pub fn build(self) -> T {
        self.payload
    }
} // impl<T> SelectBuilder<T>

impl<T> Default for SelectBuilder<T>
    where T: ::Encodable + Default
{
    fn default() -> Self {
        SelectBuilder { payload: Default::default() }
    }
} // impl Default for SelectBuilder
impl<T> SelectBuilder<T>
    where T: ::Encodable + SetSelectMethodFields
{
    pub fn no_wait(mut self, no_wait: bool) -> Self {
        SetSelectMethodFields::set_no_wait(&mut self.payload, no_wait);
        self
    } // set_no_wait()
} // impl<T> SelectBuilder<T>
pub trait SelectOkMethod {
    type Payload: Default;
} // pub trait SelectOkMethod

pub struct SelectOkBuilder<T>
    where T: ::Encodable
{
    payload: T,
} // struct SelectOkBuilder


impl<T> SelectOkBuilder<T>
    where T: Default + ::Encodable
{
    pub fn new() -> Self {
        Default::default()
    }
} // impl Builder (new)

impl<T> SelectOkBuilder<T>
    where T: ::Encodable
{
    pub fn build(self) -> T {
        self.payload
    }
} // impl<T> SelectOkBuilder<T>

impl<T> Default for SelectOkBuilder<T>
    where T: ::Encodable + Default
{
    fn default() -> Self {
        SelectOkBuilder { payload: Default::default() }
    }
} // impl Default for SelectOkBuilder
