// Copyright 2016 Alexander Reece
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

mod header_struct;
mod method_enum;
mod method_impl;
mod method_encodable_impl;
mod method_payload_impl;
mod method_struct;

use std::io;
use common::Class;

use WriteRust;

use self::header_struct::HeaderStructWriter;
use self::method_enum::MethodEnumWriter;
use self::method_impl::MethodImplWriter;
use self::method_encodable_impl::EncodableMethodImplWriter;
use self::method_payload_impl::MethodPayloadImplWriter;
use self::method_struct::MethodStructWriter;

pub struct ClassModuleWriter<'a> {
    class: &'a Class,
}

impl<'a> ClassModuleWriter<'a> {
    pub fn new(class: &'a Class) -> Self {
        ClassModuleWriter {
            class: class,
        }
    }
}

impl<'a> WriteRust for ClassModuleWriter<'a> {
    fn write_rust_to<W>(&self, writer: &mut W) -> io::Result<()>
        where W: io::Write
    {
        try!(writeln!(writer, "\n// generated by primalgen::codegen::spec_module::class_mod::ClassModuleWriter"));
        try!(writeln!(writer, "pub mod {} {{", self.class.snake_case()));
        let header = HeaderStructWriter::new(self.class);
        try!(header.write_to(writer));

        for method in self.class.methods() {
            // write the struct and its implementations
            let struct_writer = MethodStructWriter::new(method);
            try!(struct_writer.write_rust_to(writer));

            let inherit_impl = MethodImplWriter::new(method);
            try!(inherit_impl.write_rust_to(writer));

            let encodable_impl = EncodableMethodImplWriter::new(method);
            try!(encodable_impl.write_rust_to(writer));

            let payload_impl = MethodPayloadImplWriter::new(self.class, method);
            try!(payload_impl.write_rust_to(writer));
        }

        let method_enum = MethodEnumWriter::new(self.class);
        try!(method_enum.write_rust_to(writer));

        try!(writeln!(writer, "}} // mod {}", self.class.snake_case()));

        Ok(())
    }
}